/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 GithubIcon.gltf -d
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

function GithubIcon(props) {
  
  const mesh = useRef()
  useFrame ( () => (mesh.current.rotation.y -= 0.01))

  const { nodes, materials } = useGLTF('/GithubIcon.gltf')

  return (
    <group {...props} dispose={null} scale={4} ref={mesh}>
      <mesh geometry={nodes.Cylinder.geometry} material={materials.Material} position={[0, 0, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.9, 0.61, 0.9]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Material Purple']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve.geometry} material={materials['Material White']} position={[-0.02, -0.04, 0.17]} rotation={[Math.PI / 2, 0, 0]} scale={[80.52, 58.26, 80.52]} />
      <mesh geometry={nodes.Curve001.geometry} material={materials['Material White']} position={[-0.02, -0.04, -0.06]} rotation={[Math.PI / 2, 0, 0]} scale={[80.52, 58.26, 80.52]} />
    </group>
  )
}

useGLTF.preload('/GithubIcon.gltf')

export default GithubIcon