/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 PacmanIcon.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

function PacmanIcon(props) {
  
  const mesh = useRef()
  useFrame ( () => (mesh.current.rotation.y += 0.01))

  const { nodes, materials } = useGLTF('/PacmanIcon.gltf')

  return (
    <group {...props} dispose={null} scale={1.1} ref={mesh}>
      <mesh geometry={nodes.Sphere002.geometry} material={materials.spheres} position={[0.66, 0, 0]} />
      <mesh geometry={nodes.Sphere003.geometry} material={materials.spheres} position={[1.34, 0, 0]} />
      <mesh geometry={nodes.Sphere004.geometry} material={materials.spheres} position={[2.02, 0, 0]} />
      <mesh geometry={nodes.Circle.geometry} material={materials.eyes} position={[0, 0.55, 0.85]} rotation={[1.11, 1.04, -0.07]} scale={0.3} />
      <group rotation={[0, 0, 2.58]}>
        <mesh geometry={nodes.Sphere001_1.geometry} material={materials.pacman} />
        <mesh geometry={nodes.Sphere001_2.geometry} material={materials.Material} />
      </group>
      <group rotation={[0, 0, 0.54]}>
        <mesh geometry={nodes.Sphere005_1.geometry} material={materials.pacman} />
        <mesh geometry={nodes.Sphere005_2.geometry} material={materials.Material} />
      </group>
    </group>
  )
}

useGLTF.preload('/PacmanIcon.gltf')

export default PacmanIcon