/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 SnakeIcon.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export function SnakeIcon(props) {

  const mesh = useRef()
  useFrame ( () => (mesh.current.rotation.y -= 0.01))

  const { nodes, materials } = useGLTF('/SnakeIcon.gltf')

  return (
    <group {...props} dispose={null} scale={.85} ref={mesh}>
      <group position={[0.9, -2, 0]} scale={[11.04, 1.53, 1.53]}>
        <mesh geometry={nodes.Cube001.geometry} material={materials.snake} />
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} position={[0.14, 2.06, 0.17]} scale={[-0.01, -0.07, -0.07]}>
          <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[-0.69, -0.01, -1.05]} rotation={[1.72, 0.77, 2.93]} scale={-0.35} />
        </mesh>
        <mesh geometry={nodes.Sphere001.geometry} material={materials['Material.001']} position={[0.14, 2.06, -0.04]} scale={[-0.01, -0.07, -0.07]}>
          <mesh geometry={nodes.Plane001.geometry} material={materials['Material.002']} position={[-0.42, -0.01, 1.06]} rotation={[-1.41, 0.77, 2.93]} scale={-0.35} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/SnakeIcon.gltf')

export default SnakeIcon